### ISSUE TITLE
Easy way to detect if the C lib is present?

### ISSUE THREAD

**Issue by Cadair** [quintusdias/glymur#317]
What is the best way to determine if there is a c lib present? I am trying to write some code which will read the header even if there is no underlying c lib, and the data as well if there is.

**Comment by quintusdias** [comment]
Hi Stuart, this code fragment should work

```
if glymur.lib.openjp2.OPENJP2 is None and glymur.lib.openjpeg.OPENJPEG is None:
    do stuff assuming no C library was found
else:
    do other stuff assuming the C really was found
```

**Comment by Cadair** [comment]
Thanks a lot!
