### ISSUE TITLE
Make glymur conda aware

### ISSUE THREAD

**Issue by Cadair** [quintusdias/glymur#385]
I don't really know if this is possible or how it would work, but at the moment we have to tell glymur where the openjpeg library is if it's installed via conda, I don't know if this is just for our CI or a wider problem.

It would be good if the correct directory could be added to the default search path or similar.

https://github.com/sunpy/sunpy/blob/master/continuous-integration/travis/openjpeg.sh

**Comment by quintusdias** [comment]
It's possible.  The existing machinery to figure out where the library
might be can be extended such that if the library isn't found via other
methods and if the platform is anaconda, one can look in the anaconda root
directory.



On Thu, May 19, 2016 at 3:39 PM, Stuart Mumford <notifications@github.com>
wrote:

> I don't really know if this is possible or how it would work, but at the
> moment we have to tell glymur where the openjpeg library is if it's
> installed via conda, I don't know if this is just for our CI or a wider
> problem.
>
> It would be good if the correct directory could be added to the default
> search path or similar.
>
>
> https://github.com/sunpy/sunpy/blob/master/continuous-integration/travis/openjpeg.sh
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/quintusdias/glymur/issues/385>
>



-- 
John Evans

**Comment by quintusdias** [comment]
0.8.4 release candidate up on pypi, pushed to github.  Includes anaconda
awareness.  Passes tests locally on 64-bit windows, linux, osx with
openjpeg-2.1 built on conda-forge.  If no issues found, will finalize 0.8.4
release tomorrow.

On Thu, May 19, 2016 at 5:44 PM, John Evans <john.g.evans.ne@gmail.com>
wrote:

> It's possible.  The existing machinery to figure out where the library
> might be can be extended such that if the library isn't found via other
> methods and if the platform is anaconda, one can look in the anaconda root
> directory.
>
>
>
> On Thu, May 19, 2016 at 3:39 PM, Stuart Mumford <notifications@github.com>
> wrote:
>
>> I don't really know if this is possible or how it would work, but at the
>> moment we have to tell glymur where the openjpeg library is if it's
>> installed via conda, I don't know if this is just for our CI or a wider
>> problem.
>>
>> It would be good if the correct directory could be added to the default
>> search path or similar.
>>
>>
>> https://github.com/sunpy/sunpy/blob/master/continuous-integration/travis/openjpeg.sh
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/quintusdias/glymur/issues/385>
>>
>
>
>
> --
> John Evans
>



-- 
John Evans
