### ISSUE TITLE
writing metadata in jpeg2000 image file?

### ISSUE THREAD

**Issue by jslavin** [quintusdias/glymur#394]
In the example given of writing a jpeg2000 image, there's no mention of metadata.  Is there a way to include metadata in a file written by glymur?

**Comment by quintusdias** [comment]
Hi Jonathan, where is the example are you looking at?  There are a few examples given at  https://glymur.readthedocs.io/en/latest/how_do_i.html , the most detailed of which describe creating XML and UUID/XMP boxes.

**Comment by jslavin** [comment]
The piece that I'm missing is how to include metadata when writing an image.  Maybe it's there somewhere, but I haven't found it yet.

**Comment by quintusdias** [comment]
The "writing an image" part really just concentrates on writing the codestream along with an optional JP2 set of default boxes (signature, file type, and header) which don't allow for any custom metadata.  You can, however, append XML boxes to a JP2 file after the fact, e.g.  https://glymur.readthedocs.io/en/v0.8.5/how_do_i.html#add-xml-metadata

**Comment by quintusdias** [comment]
No further action planned.
