### ISSUE TITLE
Remove python 3.3 support from LTS

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/glymur#429]
All support for python 3.3 stopped on 2017-09-29, so remove the 3.3 test build on travis-ci

**Comment by hugovk** [comment]
+1

Here's the pip installs for glymur from PyPI for the last month (via `pypinfo --percent --pip glymur pyversion`), showing no 3.3:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |   44.5% |            374 |
| 2.7            |   37.3% |            314 |
| 3.5            |   16.2% |            136 |
| 3.4            |    2.0% |             17 |

**Comment by quintusdias** [comment]
Done!

**Comment by hugovk** [comment]
Don't forget to update README and setup.py.
