### ISSUE TITLE
Unrecognized box encountered (...) at byte offset 77

### ISSUE THREAD

**Issue by franfcunha** [quintusdias/glymur#432]
I am so sorry for being here asking something again but unfortunately digging into jp2box.py code is being hard to me.
I was testing my frozen Python application using glymur and when I try to access my .jp2 files in order to render some previews of them at low-resolution i receive the following error:

"UserWarning: Unrecognized box (b'jvsv') encountered at byte offset 77.
Can anyone advice me on how to handle such problem?

Thanks in advance

**Comment by quintusdias** [comment]
Sorry for just realizing this now that this was an issue someone else filed and not me.  That warning only means that a box with the ID of 'jvsv' was encountered, but 'jvsv' isn't a valid JP2 box ID, nor is it any of the known JPX box IDs.
