### ISSUE TITLE
Compression rate behaves weird! 

### ISSUE THREAD

**Issue by FarhadZanjani** [quintusdias/glymur#446]
Hi,

I used different compression rates for writing an image in the JPEG2000 format. Each time only one layer was defined for the writing function. The below is the sample code and the results:

Rate=[1]  # or [2], [4], [8], [16], [32], [64]
Img  = misc.imread(ImagePath)
jp2 = glymur.Jp2k('./tmp.jp2', data=Img, cratios=Rate)

The image file size is as below:
**Rate   1: 54    Mb
Rate   2: 54    Mb
Rate   4: 54    Mb**
Rate   8: 40.4 Mb
Rate 16: 20.2 Mb
Rate 32: 10.1 Mb
Rate 64:  5.1  Mb

As you can see, for compression rates equal to 2 and 4 the function does not perform compression!

Any comments?

**Comment by quintusdias** [comment]
Unfortunately only that this behavior holds up for the command line utility opj_compress as well, so the issue or problem is not part of glymur.
