### ISSUE TITLE
How to use multicomponent transform with glymur?

### ISSUE THREAD

**Issue by sivertba** [quintusdias/glymur#531]
Hi!

How can I use the MCT with Glymur?

**Comment by quintusdias** [comment]
Hi, I apologize, I completely missed seeing this...  

When writing an image, you can specify the mct boolean parameter to use the MCT or not to use the MCT.  

For the case of reading images, you don't currently have any choice.  If the image was created with the MCT, then the MCT is used when decoding the image.  The next release, however, adds support for the opj_set_decoded_components function in the openjpeg library, and using that function turns off the MCT.
