### ISSUE TITLE
Windows error with glymur 0.9.5

### ISSUE THREAD

**Issue by Cadair** [quintusdias/glymur#538]
Hey,

It looks like the tiff code added in 0.9.5 has a bug on windows, the [sunpy CI](https://dev.azure.com/sunpy/sunpy/_build/results?buildId=21069&view=logs&j=475592e9-b16d-5db7-f2c4-00d679a5e4fd&t=3b844151-7a1b-5533-d08f-c5dca61e3322&l=3922) is unable to import glymur on windows with the following error:

```
    import glymur
..\..\.tox\py38\lib\site-packages\glymur\__init__.py:9: in <module>
    from .tiff import Tiff2Jp2k
..\..\.tox\py38\lib\site-packages\glymur\tiff.py:13: in <module>
    from .lib import tiff as libtiff
..\..\.tox\py38\lib\site-packages\glymur\lib\tiff.py:16: in <module>
    _LIBTIFF, _LIBC = (
..\..\.tox\py38\lib\site-packages\glymur\lib\tiff.py:16: in <genexpr>
    _LIBTIFF, _LIBC = (
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\ctypes\__init__.py:451: in LoadLibrary
    return self._dlltype(name)
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\ctypes\__init__.py:363: in __init__
    if '/' in name or '\\' in name:
E   TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Cadair** [comment]
After staring at this a little longer, I am wondering if this is it failing to find libtiff on Windows?

Would it be possible to make the tiff support optional if it can't find libtiff?

**Comment by quintusdias** [comment]
That looks like what it is.  Shouldn't be too hard to fix.

**Comment by Cadair** [comment]
Thanks a lot for the super quick fix @quintusdias our test suite is passing with 0.9.6 :rocket:
