### ISSUE TITLE
Test failures on big-endian architecture (s390x)

### ISSUE THREAD

**Issue by musicinmybrain** [quintusdias/glymur#545]
While trying to update the `python-glymur` package in Fedora Linux from 0.9.6, I found there are some test failures related to the new `tiff2jp2k` tool on `s390x`—Fedora Linux’s sole big-endian architecture.

```
=========================== short test summary info ============================
FAILED tests/test_tiff2jp2.py::TestSuite::test_minisblack_3strip_to_2x2 - Zer...
FAILED tests/test_tiff2jp2.py::TestSuite::test_partial_last_strip - ZeroDivis...
FAILED tests/test_tiff2jp2.py::TestSuite::test_partial_strip_and_partial_tiles
FAILED tests/test_tiff2jp2.py::TestSuite::test_psnr - AssertionError: False i...
FAILED tests/test_tiff2jp2.py::TestSuiteNoScikitImage::test_rgb_stripped - Ze...
FAILED tests/test_tiff2jp2.py::TestSuiteNoScikitImage::test_rgb_stripped_bottom_of_tile_coincides_with_bottom_of_strip
FAILED tests/test_tiff2jp2.py::TestSuiteNoScikitImage::test_stripped_logging
============= 7 failed, 525 passed, 1 skipped in 168.62s (0:02:48) =============
```

It looks like, in each of these, `rps` (read from the `RowsPerStrip` field), is zero. I think this is because the field is actually 32-bit instead of 16-bit in this test (“`LONG`”) instead of (“`SHORT`”), and reading a 16-bit value is getting only the top half of the word on big-endian platforms.

It seems like [either type is allowed for this field](https://www.awaresystems.be/imaging/tiff/tifftags/rowsperstrip.html), and a library should use `libtiff`’s `TIFFFieldDataType` to see which is in use.

This should probably be handled automatically and generally in `glymur.lib.tiff.getFieldDefaulted()`. I’ll probably offer a PR if I have some time to work on it.

**Comment by musicinmybrain** [comment]
As a quick hack, I confirmed that hard-coding

```python
TAGS["RowsPerStrip"]["type"] = ctypes.c_uint32
```

at the end of `glymur/lib/tiff.py` makes all but one of these tests pass on all platforms. It’s not a correct fix, because `RowsPerStrip` *could* be 16-bit, but it helps confirm the diagnosis.

The exception is `tests/test_tiff2jp2.py::TestSuite::test_psnr`, which appears to be failing due to a separate issue that I haven’t looked into at all.

**Comment by quintusdias** [comment]
Thanks for the report.   I'll get to work on it.

**Comment by musicinmybrain** [comment]
Thanks! Please let me know if I can do anything to help.

**Comment by quintusdias** [comment]
Using TIFFFieldDatatype is tougher than it looks.  I elected on doing this another way, and just bypass LibTIFF when retrieving the tag values.  I already had a platform-independent way of getting all the tags for the purposes of creating a UUID box to preserve the original value of all the tags, and that should work here as well.
