### ISSUE TITLE
Un-deprecate the `read` method

### ISSUE THREAD

**Issue by ChiliJohnson** [quintusdias/glymur#548]
The `Jp2k.read` method is deprecated with a message saying that array-style slicing should be used instead, but as far as I can tell, the `read` method offers functionality that array-style slicing doesn't: specifically decoding only a specific layer and only a specific region.

For some applications it makes more sense for efficiency reasons to pull specific layers / regions out at decode time rather than load the entire image into memory and slice it up there.

Maybe the deprecation warning should only show up if there are no kwargs passed into `read`?

**Comment by quintusdias** [comment]
It actually is possible to use array-style slicing along with decoding a specific layer.  I thought I had an example of this in the docs, but I guess I do not.  I'll fix that.  There are some examples in the test suite, though.
