### ISSUE TITLE
Tiled writer fails with Access Violation when image has only one tile

### ISSUE THREAD

**Issue by Gilthans** [quintusdias/glymur#586]
Hello!
I tried running something similar to the following code:
```python3
import numpy as np
from glymur import Jp2k
jp2_image = Jp2k('artifacts/test.jp2', shape=(100, 100, 3), tilesize=(100, 100))

for tile_writer in jp2_image.get_tilewriters():
    tile_writer[:] = np.ones((100, 100, 3), dtype='uint8')
```
That is, I'm using `tilesize` that has same size as `shape`
This results in the following error:
`OSError: exception: access violation writing 0x0000000000000000`

I would expect one of two to have happened:
 1) The third line would raise an exception, that writing a single tile is invalid. This at least moves the error to the earliest possible location, and gives a lot more info than `access violation`
 2) The code would work and write the whole image in one go

The latter is preferable IMO. Obviously the example isn't very useful by itself, but happened to me on code that dynamically decided on tile sizes according to the output image size. I would have expected this to just 'work' when the image is small enough to be written with a single tile.

I'm not well versed in the Jpeg2000 format, but I would be happy to submit a PR with some pointers.
I noticed there's no `CONTRIBUTORS.md` file in the repo, so let me know if that's possible at all. If so, some guidance on how to setup the project and the guidelines would be welcome

Thanks in advance!

**Comment by quintusdias** [comment]
Thanks, I've actually seen this, but hadn't made any progress on figuring out why it's happening.  I suspect the reason is upstream in the openjpeg library, but I have no proof to back myself up there.  I'd have to write reproduction steps in C before filing a bug report with the openjpeg maintainers.

I think the thing for me to do for now is to implement your first suggestion.

**Comment by Gilthans** [comment]
I don't know the details, but the stack trace actually leads to python code failing, so I'm not sure this is the C library.
Although a better error message is definitely appreciated!
