### ISSUE TITLE
Inconsistent length member variable name in ContiguousCodestreamBox

### ISSUE THREAD

**Issue by asalamon-work** [quintusdias/glymur#588]
ContiguousCodestreamBox.\_\_init\_\_() uses length.
codestream() and parse() both use _length.

I'm trying to do something outside the box, so in normal use, this may not happen:

```
>>> newbox = glymur.jp2box.ContiguousCodestreamBox(main_header_offset=85, length=5269)
>>> newbox._filename="assembly1.jp2"
>>> newbox.codestream()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<...>/Library/Python/3.10/lib/python/site-packages/glymur/jp2box.py", line 1033, in codestream
    fptr, self._length, header_only=header_only
AttributeError: 'ContiguousCodestreamBox' object has no attribute '_length'. Did you mean: 'length'?
```

**Comment by quintusdias** [comment]
Yeah, that's a little outside the box, but I don't think there is a good reason for "_length" to be an attribute there.  Since it's an underscore attribute, I think I'm ok to remove it.  The tests all pass without the "_length" attribute.  Let me think it thru for a bit.

**Comment by asalamon-work** [comment]
Off-topic question:

Are there any active forums for asking questions about libopenjp2?

https://groups.google.com/g/openjpeg doesn't look very active, even though it's mentioned in the official GitHub new issue help.
