### ISSUE TITLE
Memory issue during loading data

### ISSUE THREAD

**Issue by Collin2046** [quintusdias/glymur#673]
I have a large image(58176, 25104, 3), which consumes lots of memory during loading. consumption from beginning 25GB to finally stable 6GB(I think this is the actual memory usage for holding the np array). Another image with larger size even could not be loaded(I have 128G memory). I am not sure what happened during loading stage.

**Comment by johnevans8msu** [comment]
sorry, didn't see this when it was opened.  the openjpeg library reads data into int32 arrays, so your image would take up 16.32 GB in that stage before coming down to 4.08 when completely moved into numpy, so that tracks.
